version: "3"

services:
  db:
    image: mysql:8.0.33
    container_name: catalog_db
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "ScoringSystem"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3305:3305"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - scoring-system

  redis:
    image: redis:alpine
    container_name: scoring_system_redis
    environment:
      REDIS_PASSWORD: pass
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/var/lib/redis"
    networks:
      - scoring-system

  api:
    build: ./api
    container_name: scoring_system_api
    environment:
      DB_URL: "mysql+mysqlconnector://root:pass@catalog_db:3305/ScoringSystem"
      REDIS_URL: "redis://redis_server:6379"
      C_FORCE_ROOT: "true"
    ports:
      - "8080:8080"
    networks:
      - scoring-system
    depends_on:
      - db

  # celery worker with ml models simulation
  worker:
    build: ./worker
    container_name: scoring_system_worker
    environment:
      REDIS_URL: "redis://redis_server:6379"
      C_FORCE_ROOT: "true"
    networks:
      - scoring-system

  frontend:
    build: ./frontend
    container_name: scoring_system_frontend
    ports:
      - "3000:3000"
    networks:
      - scoring-system

  proxy:
    image: nginx:alpine
    container_name: scoring_system_proxy
    ports:
      - "9123:9123"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - scoring-system
    depends_on:
      - api
      - frontend

volumes:
  db_data:
  nginx.conf:
  redis_data:

networks:
  scoring-system:
