services:
  catalog_db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "ScoringSystem"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3303:3303"
    volumes:
      - "catalog_data:/var/lib/mysql"
    networks:
      - scoring-system
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10

  redis_server:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: pass
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    networks:
      - scoring-system

  api:
    build: ./api
    environment:
      DB_URL: "mysql+mysqlconnector://root:pass@catalog_db:3303/ScoringSystem"
      REDIS_URL: "redis://redis_server:6379"
      C_FORCE_ROOT: "true"
    depends_on:
      catalog_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - scoring-system

  worker:
    build: ./worker
    environment:
      REDIS_URL: "redis://redis_server:6379"
      C_FORCE_ROOT: "true"
    networks:
      - scoring-system
    depends_on:
      - api
      - redis_server

volumes:
  redis_data:
  catalog_data:

networks:
  scoring-system:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16