[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "bcrypt==4.2.0",
    "onnx>=1.16.0",
    "celery==5.3.6",
    "elasticsearch==8.11.1",
    "fastapi==0.85.0",
    "mysql-connector-python==8.4.0",
    "pandas==2.2.3",
    "pydantic[email]>=1.10.24",
    "pyjwt==2.8.0",
    "pymongo==4.10.1",
    "pymysql>=1.1.2",
    "cryptography>=43.0.0",
    "python-multipart==0.0.20",
    "redis==5.0.1",
    "sqlalchemy==2.0.30",
    "sqlmodel==0.0.18",
    "uvicorn==0.18.2",
    "httpx>=0.28.1",
]
